version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'America/Santiago'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # - package-ecosystem: npm
  #   directory: '/'
  #   schedule:
  #     interval: daily
  #     time: '09:00'
  #     timezone: 'America/Santiago'
  #   open-pull-requests-limit: 5
  #   commit-message:
  #     prefix: fix
  #     prefix-development: chore
  #     include: scope
  #   labels:
  #     - 'npm dependencies'
  #   ignore:
  #     - dependency-name: '@nrwl/*'
