version: 2
updates:
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '09:00'
      timezone: 'America/Santiago'
    open-pull-requests-limit: 5
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'github-actions dependencies'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
      timezone: 'America/Santiago'
    open-pull-requests-limit: 5
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'npm dependencies'
    ignore:
      - dependency-name: '@nrwl/*'
