name: Docker builder

on: ['push']

jobs:
  build-docker-1903:
    name: build using Docker 19.03
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          # 12 LTS
          - 12.9-alpine
          - 12.10-alpine
          - 12.11-alpine
          - 12.12-alpine
          - 12.13-alpine
          - 12.14-alpine
          - 12.15-alpine
          - 12.16-alpine
          - 12.17-alpine
          - 12.18-alpine
          # 13
          - 13.10-alpine
          - 13.11-alpine
          - 13.12-alpine
          - 13.13-alpine
          - 13.14-alpine
          # 14 LTS
          - 14.6-alpine
          - 14.7-alpine
          - 14.8-alpine
          - 14.9-alpine
          - 14.10-alpine
          - 14.11-alpine
          - 14.12-alpine
          - 14.13-alpine
          - 14.14-alpine
          - 14.15-alpine
          - 15.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/19.03/Dockerfile
          tags: gperdomor/nx-docker:${{ matrix.node }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          # tags: ${{ steps.docker_meta.outputs.tags }}
          # labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ matrix.node }}

      - name: Image tags
        run: echo ${{ steps.docker_meta.outputs.tags }}

      - name: Image labels
        run: echo ${{ steps.docker_meta.outputs.labels }}

      - name: Image ditagsgest
        run: echo ${{ steps.docker_build.outputs.digest }}
